service: kebetoo-services

provider:
  name: aws
  runtime: nodejs12.x

functions:
  notifications:
    handler: services/notifications/handler.create
    events:
      - http:
          path: notifications
          method: POST
  ranking:
    handler: services/ranking/handler.rank
    events:
      - schedule: rate(5 minutes)

plugins:
  - serverless-offline
  - serverless-dotenv-plugin